import Link from "next/link";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";
import { AppShell } from "@/components/app-shell";
import { EmptyBlock, PageHeader, Panel, StatusPill } from "@/components/ui";
import { buildMeetingTaskPrefill } from "@/lib/meeting-task-prefill";
import { formatStatusLabel, getCurrentMeetingStatus } from "@/lib/dashboard-ui";
import {
  getMeeting,
  getMeetingSummary,
  getMeetingTasks,
  getMeetingTranscript,
} from "@/lib/api";
import { MeetingAIActions } from "./meeting-ai-actions";
import { MeetingTaskCreator } from "./meeting-task-creator";
import { MeetingTranscriptTabs } from "./meeting-transcript-tabs";

export const dynamic = "force-dynamic";

type Props = {
  params: Promise<{
    id: string;
  }>;
};

export default async function MeetingDetailPage({ params }: Props) {
  const { id } = await params;
  const meeting = await getMeeting(id).catch(() => null);
  if (!meeting) {
    notFound();
  }

  const [segments, summary, tasks] = await Promise.all([
    getMeetingTranscript(id).catch(() => []),
    getMeetingSummary(id).catch(() => ({ summary: "", key_points: [], decisions: [], model: null })),
    getMeetingTasks(id).catch(() => []),
  ]);
  const taskPrefill = buildMeetingTaskPrefill({
    meetingSubject: meeting.subject,
    summary: summary.summary,
    transcriptSegments: segments,
  });
  const currentStatus = getCurrentMeetingStatus(meeting);

  return (
    <AppShell>
      <div className="flex h-[calc(100vh+96px)] min-h-0 flex-col overflow-hidden p-6">
        <PageHeader
          title={meeting.subject}
          subtitle={`${formatDateTime(meeting.start_time)} - ${meeting.organizer_email ?? "Organizer unavailable"}`}
          action={
            <Link
              href="/meetings"
              className="rounded-[10px] border border-line bg-white px-3 py-2 text-xs font-medium text-ink"
            >
              Back to meetings
            </Link>
          }
        />

        <div className="mt-8 grid shrink-0 grid-cols-2 gap-4">
          <Panel>
            <p className="text-[11px] font-medium uppercase tracking-[0.06em] text-muted">Current status</p>
            <div className="mt-3">
              <StatusPill tone={currentStatus.tone}>{currentStatus.label}</StatusPill>
            </div>
          </Panel>
          <Panel>
            <p className="text-[11px] font-medium uppercase tracking-[0.06em] text-muted">Transcript lines</p>
            <p className="mt-3 text-lg font-semibold text-ink">{segments.length}</p>
          </Panel>
        </div>

        <div className="mt-5 grid min-h-0 flex-1 grid-cols-[1fr_360px] gap-5">
          <MeetingTranscriptTabs meetingId={meeting.id} segments={segments} />

          <div className="grid min-h-0 grid-rows-[minmax(0,1fr)_minmax(0,1fr)] gap-5">
            <Panel title="Summary" className="flex min-h-0 flex-col">
              <div className="min-h-0 flex-1 overflow-y-auto pr-1">
                {summary.summary || summary.key_points.length || summary.decisions.length ? (
                  <div className="space-y-4">
                    {summary.summary ? (
                      <SummarySection title="Overview" tone="brand">
                        <p className="text-justify text-xs leading-5 text-ink">{summary.summary}</p>
                      </SummarySection>
                    ) : null}
                    <SummaryList title="Key points" items={summary.key_points} tone="good" bulleted />
                    <SummaryList title="Decisions" items={summary.decisions} tone="warn" />
                    {summary.model ? (
                      <p className="font-mono text-[10px] text-muted">Generated by {summary.model}</p>
                    ) : null}
                  </div>
                ) : (
                  <EmptyBlock title="Summary pending" text="AI summary generation will run after transcript sync is available." />
                )}
              </div>
            </Panel>
            <Panel title="Meeting tasks" className="flex min-h-0 flex-col">
              <div className="min-h-0 flex-1 overflow-y-auto pr-1">
                <MeetingAIActions
                  meetingId={meeting.id}
                  hasSummary={Boolean(summary.summary)}
                  linkedTaskCount={tasks.length}
                />
                <MeetingTaskCreator meetingId={meeting.id} prefill={taskPrefill} />
                {tasks.length === 0 ? (
                  <EmptyBlock title="No linked tasks" text="Action items converted to tasks will appear here." />
                ) : (
                  <div className="space-y-3">
                    {tasks.map((task) => (
                      <div key={task.id} className="rounded-[10px] border border-line bg-[#faf9f5] p-3">
                        <div className="flex items-start justify-between gap-2">
                          <p className="text-xs font-medium leading-5 text-ink">{task.title}</p>
                          <StatusPill tone={priorityTone(task.priority)}>
                            {formatStatusLabel(task.priority ?? "medium")}
                          </StatusPill>
                        </div>
                        {task.description ? (
                          <p className="mt-2 text-xs leading-5 text-muted">{task.description}</p>
                        ) : null}
                        <div className="mt-3 flex flex-wrap gap-2 font-mono text-[10px] text-muted">
                          <span>{formatStatusLabel(task.status)}</span>
                          <span>{task.due_date ? `Due ${task.due_date}` : "No due date"}</span>
                          {task.action_item_id ? <span>Action {shortId(task.action_item_id)}</span> : null}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </Panel>
          </div>
        </div>
      </div>
    </AppShell>
  );
}

function SummarySection({
  title,
  tone,
  children,
}: {
  title: string;
  tone: "brand" | "good" | "warn";
  children: ReactNode;
}) {
  const toneClasses = {
    brand: "border-brand",
    good: "border-[#2a7a4b]",
    warn: "border-[#8a5d00]",
  };

  return (
    <section className={`border-l-2 pl-3 ${toneClasses[tone]}`}>
      <p className="text-[11px] font-medium uppercase tracking-[0.06em] text-muted">{title}</p>
      <div className="mt-2">{children}</div>
    </section>
  );
}

function SummaryList({
  title,
  items,
  tone,
  bulleted = false,
}: {
  title: string;
  items: unknown[];
  tone: "brand" | "good" | "warn";
  bulleted?: boolean;
}) {
  if (items.length === 0) {
    return null;
  }

  return (
    <SummarySection title={title} tone={tone}>
      <ul className={`space-y-2 ${bulleted ? "list-disc pl-4" : "list-none"}`}>
        {items.map((item, index) => (
          <li key={`${title}-${index}`} className="text-justify text-xs leading-5 text-ink">
            {formatSummaryItem(item)}
          </li>
        ))}
      </ul>
    </SummarySection>
  );
}

function formatSummaryItem(item: unknown) {
  if (typeof item === "string") {
    return item;
  }
  if (item && typeof item === "object") {
    const record = item as Record<string, unknown>;
    for (const key of ["text", "title", "decision", "point", "summary"]) {
      if (typeof record[key] === "string") {
        return record[key];
      }
    }
    return JSON.stringify(record);
  }
  return String(item);
}

function formatDateTime(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "Unknown time" : date.toLocaleString();
}

function priorityTone(priority?: string | null): "neutral" | "good" | "warn" | "brand" {
  if (priority === "urgent" || priority === "high") {
    return "warn";
  }
  if (priority === "low") {
    return "good";
  }
  return "neutral";
}

function shortId(value: string) {
  return value.length > 8 ? value.slice(0, 8) : value;
}
